force-app/main/default/objects/TourSaleStatus__c/TourSaleStatus__c.object-meta.xml
<CustomObject>
    <description>Tour sale status</description>
    <label>Tour Sale Status</label>
    <nameField>
        <label>Name</label>
        <type>AutoNumber</type>
        <displayFormat>TSS-{000000}</displayFormat>
    </nameField>
    <pluralLabel>Tour Sale Status</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TourSaleStatus__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Price</description>
    <label>Price</label>
    <required>true</required>
    <type>Currency</type>
    <precision>18</precision>
    <scale>2</scale>
</CustomField>

force-app/aep/service/classes/TourSaleStatusService.cls
/***************************************************************************
* This class contains methods for working with the TourSaleStatus__c object
***************************************************************************/

public with sharing class TourSaleStatusService {

    /**
     * This method recalculates the tour price according to the guests number
    **/
    public static void recalcTourPrice(Id tourId, Integer oldGuestsNumber, Integer newGuestsNumber) {
        try {
            List<TourSaleStatus__c> tssList = new TourSaleStatusSelector().selectByTourId(tourId);
            TourSaleStatus__c tourSaleStatus = tssList[0];
            tourSaleStatus.Price__c = tourSaleStatus.Price__c / oldGuestsNumber * newGuestsNumber;
            update tourSaleStatus;
        } catch (Exception ex) {
            System.debug(LoggingLevel.ERROR, ex.getMessage());
        }
    }
}