force-app/main/default/objects/Accommodation__c/Accommodation__c.object-meta.xml
<CustomObject>
    <description>Accommodation Info</description>
    <label>Accommodation</label>
    <nameField>
        <label>Accommodation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accommodation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <description>Flight information</description>
    <label>Flight</label>
    <nameField>
        <label>Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Tour__c/Tour__c.object-meta.xml
<CustomObject>
    <description>Tour information</description>
    <label>Tour</label>
    <nameField>
        <label>Tour Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Tour__c/fields/Accommodation__c.field-meta.xml
<CustomField>
    <fullName>Accommodation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Accommodation related to the tour</inlineHelpText>
    <label>Accommodation</label>
    <referenceTo>Accommodation__c</referenceTo>
    <relationshipName>Accommodation</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/general/classes/GENERAL_FieldSetHelper.cls
/********************************************************************
* This class is for storing general Fieldset help methods
********************************************************************/

public class GENERAL_FieldSetHelper {

    public static List<String> defaultFieldSets = new List<String> {
        'Standard', 'Full'
    };

    public static Schema.FieldSet getFieldSet(String objectName) {
        return getFieldSet(objectName, 'Standard');
    }

    public static Schema.FieldSet getFieldSet(String objectName, String fieldSetTypeName) {
        Schema.FieldSet fieldSet;
        fieldSetTypeName = setFieldSetName(objectName, fieldSetTypeName);
        switch on objectName {
            when 'Flight' {
                fieldSet = Schema.SObjectType.Flight__c.fieldsets.getMap().get(fieldSetTypeName);
            }
            when 'Tour' {
                fieldSet = Schema.SObjectType.Tour__c.fieldsets.getMap().get(fieldSetTypeName);
            }
            when 'Accommodation' {
                fieldSet = Schema.SObjectType.Accommodation__c.fieldsets.getMap().get(fieldSetTypeName);
            }
        }
        return fieldSet;
    }

    public static String getFieldsString(String objectName, String fieldSetTypeName) {
        List<Schema.FieldSetMember> fieldSetMembers;
        List<String> fields = new List<String>();
        fieldSetTypeName = setFieldSetName(objectName, fieldSetTypeName);
        switch on objectName {
            when 'Flight' {
                fieldSetMembers = Schema.SObjectType.Flight__c.fieldsets.getMap().get(fieldSetTypeName).getFields();
            }
            when 'Tour' {
                fieldSetMembers = Schema.SObjectType.Tour__c.fieldsets.getMap().get(fieldSetTypeName).getFields();
            }
            when 'Accommodation' {
                fieldSetMembers = Schema.SObjectType.Accommodation__c.fieldsets.getMap().get(fieldSetTypeName).getFields();
            }
        }
        for(Schema.FieldSetMember fm : fieldSetMembers) {
            fields.add(fm.getFieldPath());
        }
        return String.join(fields, ',');
    }

    public static String setFieldSetName(String objectName, String fieldSetTypeName) {
        String fieldSetForReturn = 'Standard' + objectName;
        if (defaultFieldSets.contains(fieldSetTypeName)) fieldSetForReturn = fieldSetTypeName + objectName;
        return fieldSetForReturn;
    }

}