force-app/main/default/objects/Account/fields/TravelAgency__c.field-meta.xml
<CustomField>
    <fullName>TravelAgency__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Travel agency to which account belongs</inlineHelpText>
    <label>Travel Agency</label>
    <referenceTo>TravelAgency__c</referenceTo>
    <relationshipName>A_TravelAgency</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TravelAgency__c/TravelAgency__c.object-meta.xml
<CustomObject>
    <description>Travel Agency</description>
    <label>Travel Agency</label>
    <nameField>
        <label>Travel Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travel Agencies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TravelAgency__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Travel agency level</description>
    <required>true</required>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Level A</fullName>
                <default>true</default>
                <label>A</label>
            </value>
            <value>
                <fullName>Level B</fullName>
                <label>B</label>
            </value>
            <value>
                <fullName>Level C</fullName>
                <label>C</label>
            </value>
            <value>
                <fullName>Level D</fullName>
                <label>D</label>
            </value>
            <value>
                <fullName>Level E</fullName>
                <label>E</label>
            </value>
            <value>
                <fullName>Level F</fullName>
                <label>F</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/test/classes/AccountSelectorTest.cls
/*****************************************************************
* This class contains test methods for the AccountSelector class
*****************************************************************/

@isTest
public class AccountSelectorTest {

    @isTest
    static void selectByIdWithDynamicFieldList() {
        Account account = GENERAL_TestAccountFactory.createByNumber(1)[0];
        List<String> fields = new List<String> {'NaicsCode' };
        List<Account> selectedAccounts = new AccountSelector().selectById(account.Id, fields);
        System.assert(String.isNotBlank(selectedAccounts[0].NaicsCode),
            'ShippingAddress field should be in the response');
    }

    @isTest
    static void selectByIdWithDynamicFieldString() {
        Account account = GENERAL_TestAccountFactory.createByNumber(1)[0];
        String stringFields = 'NaicsCode';
        List<Account> selectedAccounts = new AccountSelector().selectById(account.Id, stringFields);
        System.assert(String.isNotBlank(selectedAccounts[0].NaicsCode),
            'ShippingAddress field should be in the response');
    }

    @isTest
    static void selectByTravelAgencyId() {
       TravelAgency__c travelAgency = GENERAL_TestTravelAgencyFactory.createSingle().get();
        Account account =
            GENERAL_TestAccountFactory.createSingle()
                .withTravelAgency(travelAgency)
                .get();
       List<Account> accounts = new AccountSelector().selectByTravelAgencyId(travelAgency.Id);
       System.assertEquals(accounts[0].TravelAgency__c, travelAgency.Id, 'Travel Agency Id should be equals travelAgency.Id');
       System.assertEquals(accounts.size(), 1, 'Size should meet the expectations (1)');
    }

    @isTest
    static void selectByTravelAgencyName() {
        TravelAgency__c travelAgency =
            GENERAL_TestTravelAgencyFactory.createSingle()
                .withName('TravelAgency1')
                .get();
        Account account =
            GENERAL_TestAccountFactory.createSingle()
                .withTravelAgency(travelAgency)
                .get();
        List<Account> accounts = new AccountSelector().selectByTravelAgencyName('TravelAgency1');
        System.assertEquals(accounts[0].TravelAgency__r.Name, 'TravelAgency1', 'Travel Agency name should be TravelAgency1');
        System.assertEquals(accounts.size(), 1, 'Size should meet the expectations (1)');
    }

    @isTest
    static void selectByTravelAgencyLevel() {
       TravelAgency__c travelAgency =
            GENERAL_TestTravelAgencyFactory.createSingle()
                .withLevel('Level A')
                .get();
        Account account =
            GENERAL_TestAccountFactory.createSingle()
                .withTravelAgency(travelAgency)
                .get();
       List<Account> accounts = new AccountSelector().selectByTravelAgencyLevel('A');
       System.assertEquals(accounts[0].TravelAgency__r.Level__c, 'A', 'Travel Agency level should be equals A');
       System.assertEquals(accounts.size(), 1, 'Size should meet the expectations (1)');
    }
}