force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <description>Flight information</description>
    <label>Flight</label>
    <nameField>
        <label>Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight__c/fields/Aircraft__c.field-meta.xml
<CustomField>
    <fullName>Aircraft__c</fullName>
    <description>Aircraft</description>
    <label>Aircraft</label>
    <type>Text</type>
    <length>30</length>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Airlines__c.field-meta.xml
<CustomField>
    <fullName>Airlines__c</fullName>
    <description>Airlines</description>
    <label>Airlines</label>
    <required>true</required>
    <type>Text</type>
    <length>255</length>
</CustomField>

force-app/main/default/objects/Flight__c/fields/ArrivalTime__c.field-meta.xml
<CustomField>
    <fullName>ArrivalTime__c</fullName>
    <description>Flight arrival time</description>
    <label>Arrival Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Departure__c.field-meta.xml
<CustomField>
    <fullName>Departure__c</fullName>
    <description>Departure airport code (IATA)</description>
    <label>Departure</label>
    <required>true</required>
    <type>Text</type>
    <length>3</length>
</CustomField>

force-app/main/default/objects/Flight__c/fields/DepartureTime__c.field-meta.xml
<CustomField>
    <fullName>DepartureTime__c</fullName>
    <description>Flight departure time</description>
    <label>Departure Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <description>Destination airport code (IATA)</description>
    <label>Destination</label>
    <required>true</required>
    <type>Text</type>
    <length>3</length>
</CustomField>

force-app/main/default/objects/Flight__c/fields/PNR__c.field-meta.xml
<CustomField>
    <fullName>PNR__c</fullName>
    <description>Passenger Name Record</description>
    <label>PNR</label>
    <required>true</required>
    <type>Text</type>
    <length>6</length>
</CustomField>

force-app/general-test/test-sobject-creator/classes/GENERAL_TestFlightCreator.cls
/********************************************************************
* This class is for creating instances of Flight__c object
********************************************************************/

@isTest
public with sharing class GENERAL_TestFlightCreator {

    /**
     * List of available test aircrafts
    **/
    public static List<String> aircrafts = new List<String> {
        'Boeing 787-8', 'Boeing 787-9', 'Boeing 787-10',
        'Airbus A380-800', 'Airbus A380-900', 'Airbus A380-10000'
    };

    /**
     * List of available test departures codes
    **/
    public static List<String> departures = new List<String> {
        'SVO', 'DME', 'VKO'
    };

    /**
     * List of available test destinations codes
    **/
    public static List<String> destinations = new List<String> {
        'DXB', 'DHF', 'DIA'
    };

    /**
     * List of available test airlines
    **/
    public static List<String> airlines = new List<String> {
        'Emirates', 'Etihad', 'Qatar Airways'
    };

    /**
     * List of available test PNR codes
    **/
    public static List<String> PNRs = new List<String> {
        'A1A1A1', 'B2B2B2', 'C3C3C3'
    };

    /**
     * This method creates List<Flight__c> by input number
    **/
    public static List<Flight__c> create(Integer flightNumber) {
        List<Flight__c> flights = new List<Flight__c>();
        for (Integer i = 0; i < flightNumber; i++) {
            flights.Add(
                new Flight__c(
                    Name = 'Flight' + DateTime.now().getTime(),
                    Aircraft__c = GENERAL_TestUtils.randomSelect(aircrafts),
                    Departure__c = GENERAL_TestUtils.randomSelect(departures),
                    Destination__c = GENERAL_TestUtils.randomSelect(destinations),
                    DepartureTime__c = DateTime.now(),
                    ArrivalTime__c = DateTime.now(),
                    Airlines__c = GENERAL_TestUtils.randomSelect(airlines),
                    PNR__c = GENERAL_TestUtils.randomSelect(PNRs)
                )
            );
        }
        return flights;
    }
}