force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <description>Flight information</description>
    <label>Flight</label>
    <nameField>
        <label>Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight__c/fields/Airlines__c.field-meta.xml
<CustomField>
    <fullName>Airlines__c</fullName>
    <description>Airlines</description>
    <label>Airlines</label>
    <required>true</required>
    <type>Text</type>
    <length>255</length>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Departure__c.field-meta.xml
<CustomField>
    <fullName>Departure__c</fullName>
    <description>Departure airport code (IATA)</description>
    <label>Departure</label>
    <required>true</required>
    <type>Text</type>
    <length>3</length>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <description>Destination airport code (IATA)</description>
    <label>Destination</label>
    <required>true</required>
    <type>Text</type>
    <length>3</length>
</CustomField>

force-app/main/default/objects/Flight__c/fields/FlightNumber__c.field-meta.xml
<CustomField>
    <fullName>FlightNumber__c</fullName>
    <description>Flight Number</description>
    <label>Flight Number</label>
    <type>Text</type>
    <length>8</length>
</CustomField>

force-app/main/default/objects/Flight__c/fields/PNR__c.field-meta.xml
<CustomField>
    <fullName>PNR__c</fullName>
    <description>Passenger Name Record</description>
    <label>PNR</label>
    <required>true</required>
    <type>Text</type>
    <length>6</length>
</CustomField>

force-app/aep/selector/classes/FlightSelector.cls
/**************************************************************************
* This class contains methods for generating query to the Flight__c object
**************************************************************************/

public with sharing class FlightSelector extends GENERAL_SObjectSelector {

    public FlightSelector() {}

    public FlightSelector(String fieldSetName) {
        super(fieldSetName);
    }

    public SObjectType getSObjectType() {
        return Flight__c.SObjectType;
    }

    public override SObjectType genGetSObjectType() {
        return Flight__c.SObjectType;
    }

    /**
     * Default fields of Flight__c object
    **/
    public List<SObjectField> getSObjectFieldList() {
        return new List<SObjectField> {
            Flight__c.Id,
            Flight__c.Departure__c,
            Flight__c.Destination__c,
            Flight__c.FlightNumber__c,
            Flight__c.Airlines__c,
            Flight__c.PNR__c
        };
    }

    // public List<Schema.FieldSet> getSObjectFieldSetList()
    // {
    //     if(!String.isBnank(this.fieldSetName))
    //         return new List<Schema.FieldSet> {
    //             GENERAL_FieldSetHelper.getFieldSet(
    //                 this.getSObjectType().getDescribe().getLabel(),
    //                 this.fieldSetName
    //             )
    //         };
    //     return null;
    // }

    /**
     * This method selects the flights by their PNR codes
    **/
    public List<Flight__c> selectByPNR(String pnr) {
        return Database.query(
            newQueryFactory()
                .setCondition('PNR__c = :pnr')
                .ToSOQl()
            );
    }

    /**
     * This method selects the flights by AirLines name
    **/
    public List<Flight__c> selectByAirlines(String airLines) {
        String airLinesName = airLines + '%';
        return Database.query(
            newQueryFactory()
                .setCondition('Airlines__c LIKE :airLinesName')
                .ToSOQl()
            );
    }
}