force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <description>Flight information</description>
    <label>Flight</label>
    <nameField>
        <label>Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight__c/fields/FlightNumber__c.field-meta.xml
<CustomField>
    <fullName>FlightNumber__c</fullName>
    <description>Flight Number</description>
    <label>Flight Number</label>
    <type>Text</type>
    <length>8</length>
</CustomField>

force-app/main/default/objects/Flight__c/fields/PNR__c.field-meta.xml
<CustomField>
    <fullName>PNR__c</fullName>
    <description>Passenger Name Record</description>
    <label>PNR</label>
    <required>true</required>
    <type>Text</type>
    <length>6</length>
</CustomField>

force-app/main/default/objects/Tour__c/Tour__c.object-meta.xml
<CustomObject>
    <description>Tour information</description>
    <label>Tour</label>
    <nameField>
        <label>Tour Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TourFlight__c/TourFlight__c.object-meta.xml
<CustomObject>
    <description>Junction object to link between the flights and the tours</description>
    <label>Tour - Flight</label>
    <nameField>
        <label>Tour Flight Name</label>
        <type>AutoNumber</type>
        <displayFormat>TF-{000000}</displayFormat>
    </nameField>
    <pluralLabel>Tour - Flight</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TourFlight__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipName>TF_Flight</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TourFlight__c/fields/Tour__c.field-meta.xml
<CustomField>
    <fullName>Tour__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tour</label>
    <referenceTo>Tour__c</referenceTo>
    <relationshipName>TF_Tour</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/aep/selector/classes/TourFlightSelector.cls
/******************************************************************************
* This class contains methods for generating query to the TourFlight__c object
******************************************************************************/

public class TourFlightSelector extends GENERAL_SObjectSelector {

    public SObjectType getSObjectType() {
        return TourFlight__c.SObjectType;
    }

    /**
     * Default fields of TourFlight__c object
    **/
    public List<SObjectField> getSObjectFieldList() {
        return new List<SObjectField> {
            TourFlight__c.Id,
            TourFlight__c.Tour__c,
            TourFlight__c.Flight__c
        };
    }

    /**
     * This method selects TourFlight by its flight PNR
    **/
    public List<TourFlight__c> selectByFlightPNR(String pnr) {
        String flightRelationship = TourFlight__c.Flight__c.getDescribe().getRelationshipName();
        return Database.query(
            newQueryFactory()
                .setCondition(flightRelationship + '.PNR__c = :pnr')
                .ToSOQl()
            );
    }

    /**
     * This method selects TourFlights by their  flight Number
    **/
    public List<TourFlight__c> selectByFlightNumber(String flightNumber) {
        String flightRelationship = TourFlight__c.Flight__c.getDescribe().getRelationshipName();
        return Database.query(
            newQueryFactory()
                .setCondition(flightRelationship + '.FlightNumber__c = :flightNumber')
                .ToSOQl()
            );
    }

    /**
     * This method selects TourFlights by Tour ids
     * (subselect, need refactoring)
    **/
    public List<TourFlight__c> selectByTourId(Set<Id> idSet) {
        String flightRelationship = TourFlight__c.Flight__c.getDescribe().getRelationshipName();
        String tourRelationship = TourFlight__c.Tour__c.getDescribe().getRelationshipName();
        fflib_QueryFactory tourFlightQF = newQueryFactory()
            .setCondition('Tour__c in :idSet');

        Schema.FieldSet standardFlightFieldSet = GENERAL_FieldSetHelper.getFieldSet('Flight');
        Schema.FieldSet standardTourFieldSet = GENERAL_FieldSetHelper.getFieldSet('Tour');

        fflib_QueryFactory tourQF = new TourSelector()
            .addQueryFactorySubselect(tourFlightQF, tourRelationship)
            .selectFieldSet(standardTourFieldSet);

        fflib_QueryFactory flightQF = tourFlightQF.subSelectQuery(flightRelationship)
            .selectFieldSet(standardFlightFieldSet);

        return Database.query(tourFlightQF.ToSOQl());
    }
}