force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <description>Flight information</description>
    <label>Flight</label>
    <nameField>
        <label>Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight__c/fields/PNR__c.field-meta.xml
<CustomField>
    <fullName>PNR__c</fullName>
    <description>Passenger Name Record</description>
    <label>PNR</label>
    <required>true</required>
    <type>Text</type>
    <length>6</length>
</CustomField>

force-app/main/default/objects/Tour__c/Tour__c.object-meta.xml
<CustomObject>
    <description>Tour information</description>
    <label>Tour</label>
    <nameField>
        <label>Tour Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Tour__c/fields/BeginDate__c.field-meta.xml
<CustomField>
    <fullName>BeginDate__c</fullName>
    <description>Tour begin date</description>
    <label>Begin Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tour__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>Tour end date</description>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tour__c/fields/GuestsNumber__c.field-meta.xml
<CustomField>
    <fullName>GuestsNumber__c</fullName>
    <description>Number of guests</description>
    <label>Guests number</label>
    <required>true</required>
    <type>Number</type>
    <precision>18</precision>
    <scale>0</scale>
</CustomField>

force-app/main/default/objects/Tour__c/fields/Visa__c.field-meta.xml
<CustomField>
    <fullName>Visa__c</fullName>
    <description>Visa requirement</description>
    <label>Visa</label>
    <type>Checkbox</type>
    <defaultValue>false</defaultValue>
</CustomField>

force-app/main/default/objects/TourFlight__c/TourFlight__c.object-meta.xml
<CustomObject>
    <description>Junction object to link between the flights and the tours</description>
    <label>Tour - Flight</label>
    <nameField>
        <label>Tour Flight Name</label>
        <type>AutoNumber</type>
        <displayFormat>TF-{000000}</displayFormat>
    </nameField>
    <pluralLabel>Tour - Flight</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TourFlight__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flight__c</referenceTo>
    <relationshipName>TF_Flight</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TourFlight__c/fields/Tour__c.field-meta.xml
<CustomField>
    <fullName>Tour__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tour</label>
    <referenceTo>Tour__c</referenceTo>
    <relationshipName>TF_Tour</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/aep/selector/classes/TourSelector.cls
/*********************************************************************
* This class contains methods for generating query to the Tour object
*********************************************************************/

public with sharing class TourSelector extends GENERAL_SObjectSelector {

    public SObjectType getSObjectType() {
        return Tour__c.SObjectType;
    }

    /**
     * Defaulf fields of Tour__c object
    **/
    public List<SObjectField> getSObjectFieldList() {
        return new List<SObjectField> {
            Tour__c.Id,
            Tour__c.BeginDate__c,
            Tour__c.EndDate__c,
            Tour__c.GuestsNumber__c,
            Tour__c.Visa__c
        };
    }

    /**
     * This method selects Tour__c by its flight PNR
    **/
    public List<Tour__c> selectByFlightPNR(String pnr) {
        List<TourFlight__c> tfList = [SELECT Tour__c FROM TourFlight__c WHERE TourFlight__c.Flight__r.PNR__c = :pnr];
        Set<Id> idSet = new Set<Id>();
        for (TourFlight__c tf : tfList) idSet.Add(tf.Tour__c);
        return Database.query(
            newQueryFactory()
                .setCondition('Id IN :idSet')
                .ToSOQl()
            );
    }
}