force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <description>Flight information</description>
    <label>Flight</label>
    <nameField>
        <label>Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight__c/fields/PNR__c.field-meta.xml
<CustomField>
    <fullName>PNR__c</fullName>
    <description>Passenger Name Record</description>
    <label>PNR</label>
    <required>true</required>
    <type>Text</type>
    <length>6</length>
</CustomField>

force-app/test/classes/FlightSelectorTest.cls
/***************************************************************
* This class contains test methods for the FlightSelector class
***************************************************************/

@isTest
public with sharing class FlightSelectorTest {

    @isTest
    static void selectByPNR() {
        Flight__c flight =
            GENERAL_TestFlightFactory.createSingle()
                .withPNR('D4D4D4')
                .get();
        List<Flight__c> flights = new FlightSelector('Full').selectByPNR('D4D4D4');
        System.debug(flights[0]);
        System.assertEquals(flights[0].PNR__c, 'D4D4D4', 'PNR should be D4D4D4');
        System.assertEquals(flights.size(), 1, 'Size should meet the expectations (1)');
    }
}