force-app/main/default/objects/TravelAgency__c/TravelAgency__c.object-meta.xml
<CustomObject>
    <description>Travel Agency</description>
    <label>Travel Agency</label>
    <nameField>
        <label>Travel Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travel Agencies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TravelAgency__c/fields/ActivityStatus__c.field-meta.xml
<CustomField>
    <fullName>ActivityStatus__c</fullName>
    <description>Travel agency activity status</description>
    <required>true</required>
    <label>Activity Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Limited Access</fullName>
                <label>Limited</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TravelAgency__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Travel agency level</description>
    <required>true</required>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Level A</fullName>
                <default>true</default>
                <label>A</label>
            </value>
            <value>
                <fullName>Level B</fullName>
                <label>B</label>
            </value>
            <value>
                <fullName>Level C</fullName>
                <label>C</label>
            </value>
            <value>
                <fullName>Level D</fullName>
                <label>D</label>
            </value>
            <value>
                <fullName>Level E</fullName>
                <label>E</label>
            </value>
            <value>
                <fullName>Level F</fullName>
                <label>F</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/general-test/test-sobject-creator/classes/GENERAL_TestTravelAgencyCreator.cls
/********************************************************************
* This class is for creating instances of TravelAgency__c object
********************************************************************/

@isTest
public with sharing class GENERAL_TestTravelAgencyCreator {

    /**
     * List of available test activity statuses
    **/
    public static List<String> activityStatuses = new List<String> {
        'Active', 'Blocked', 'Limited Access'
    };

    /**
     * List of available test levels
    **/
    public static List<String> levels = new List<String> {
        'Level A', 'Level B', 'Level C'
    };

    /**
     * This method creates List<TravelAgency__c> by input number
    **/
    public static List<TravelAgency__c> create(Integer travelAgencyNumber) {
        List<TravelAgency__c> travelAgencies = new List<TravelAgency__c>();
        for (Integer i = 0; i < travelAgencyNumber; i++) {
            travelAgencies.Add(
                new TravelAgency__c(
                    Name = 'TravelAgency' + DateTime.now().getTime(),
                    ActivityStatus__c = GENERAL_TestUtils.randomSelect(activityStatuses),
                    Level__c = GENERAL_TestUtils.randomSelect(levels)
                )
            );
        }
        return travelAgencies;
    }
}