force-app/main/default/objects/TravelAgency__c/TravelAgency__c.object-meta.xml
<CustomObject>
    <description>Travel Agency</description>
    <label>Travel Agency</label>
    <nameField>
        <label>Travel Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travel Agencies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TravelAgency__c/fields/ActivityStatus__c.field-meta.xml
<CustomField>
    <fullName>ActivityStatus__c</fullName>
    <description>Travel agency activity status</description>
    <required>true</required>
    <label>Activity Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Limited Access</fullName>
                <label>Limited</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TravelAgency__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Travel agency level</description>
    <required>true</required>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Level A</fullName>
                <default>true</default>
                <label>A</label>
            </value>
            <value>
                <fullName>Level B</fullName>
                <label>B</label>
            </value>
            <value>
                <fullName>Level C</fullName>
                <label>C</label>
            </value>
            <value>
                <fullName>Level D</fullName>
                <label>D</label>
            </value>
            <value>
                <fullName>Level E</fullName>
                <label>E</label>
            </value>
            <value>
                <fullName>Level F</fullName>
                <label>F</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/aep/service/classes/TravelAgencyService.cls
/*************************************************************************
* This class contains methods for working with the TravelAgency__c object
*************************************************************************/

public with sharing class TravelAgencyService {

    /**
     * This is an example of Level and Status dependency
    **/
    private final Map<String, String> levelStatusMapping = new Map<String, String> {
        'Level A' => 'Active',
        'Level B' => 'Active',
        'Level C' => 'Limited Access',
        'Level D' => 'Limited Access',
        'Level E' => 'Limited Access',
        'Level F' => 'Blocked'
    };

    public void setStatusByLevel(List<TravelAgency__c> newRecordsList) {
        try {
            for(TravelAgency__c ta : newRecordsList) {
                ta.ActivityStatus__c = levelStatusMapping.get(ta.Level__c);
            }
        } catch (Exception ex) {
            System.debug(LoggingLevel.ERROR, ex.getMessage());
        }
    }

    /**
     * This method checks Blocked status for futher calling revoke method
    **/
    public void checkBlockedTravelAgency(List<TravelAgency__c> newRecordsList) {
        Set<Id> taBlockedSet = new Set<Id>();
        try {
            for(TravelAgency__c ta : newRecordsList) {
                if (ta.ActivityStatus__c == 'Blocked')
                    taBlockedSet.add(ta.Id);
            }
            if (taBlockedSet.size() > 0)
                revokeTravelAgencyToken(taBlockedSet);
        } catch (Exception ex) {
            System.debug(LoggingLevel.ERROR, ex.getMessage());
        }
    }

    /**
     * This method starts revoking tokens for blocked Travel agencies
    **/
    public void revokeTravelAgencyToken(Set<Id> taIdSet) {
        if (taIdSet.size() > 0)
            System.enqueueJob(new OauthTokenRevokeQueueable(taIdSet));
    }

}