force-app/main/default/objects/TravelAgency__c/TravelAgency__c.object-meta.xml
<CustomObject>
    <description>Travel Agency</description>
    <label>Travel Agency</label>
    <nameField>
        <label>Travel Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travel Agencies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TravelAgency__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Travel agency level</description>
    <required>true</required>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Level A</fullName>
                <default>true</default>
                <label>A</label>
            </value>
            <value>
                <fullName>Level B</fullName>
                <label>B</label>
            </value>
            <value>
                <fullName>Level C</fullName>
                <label>C</label>
            </value>
            <value>
                <fullName>Level D</fullName>
                <label>D</label>
            </value>
            <value>
                <fullName>Level E</fullName>
                <label>E</label>
            </value>
            <value>
                <fullName>Level F</fullName>
                <label>F</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/aep/domain/classes/TravelAgencyDomain.cls
/******************************************************************************
* This class is for facilitating actions occuring on the TravelAgency__c object
******************************************************************************/

public with sharing class TravelAgencyDomain extends fflib_SObjectDomain {

    /**
     * Constructor to the TravelAgencyDomain class
    **/
    public TravelAgencyDomain(List<TravelAgency__c> travelAgencyList) {
        super((List<SObject>) travelAgencyList);
    }

    /**
     * This method is used to set the TravelAgency__c.Status__c
     * depending on the TravelAgency__c.Level__c
    **/
    public override void onBeforeUpdate(Map<Id, SObject> oldMap) {
        try {
            new TravelAgencyService().setStatusByLevel((List<TravelAgency__c>)Records);
        } catch (Exception ex) {
            System.debug(LoggingLevel.ERROR, ex.getMessage());
        }
    }

    /**
     * This method is used to check the TravelAgency__c.Status__c
     * for futher access token revoking
    **/
    public override void onAfterUpdate(Map<Id, SObject> oldMap) {
        try {
            new TravelAgencyService().checkBlockedTravelAgency((List<TravelAgency__c>)Records);
        } catch (Exception ex) {
            System.debug(LoggingLevel.ERROR, ex.getMessage());
        }
    }

    /**
     * An inner class to the TravelAgencyDomain class, supported here for test purposes
    **/
    public class Constructor implements IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new TravelAgencyDomain(sObjectList);
        }
    }
}