force-app/main/default/objects/TravelAgency__c/TravelAgency__c.object-meta.xml
<CustomObject>
    <description>Travel Agency</description>
    <label>Travel Agency</label>
    <nameField>
        <label>Travel Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travel Agencies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TravelAgency__c/fields/ActivityStatus__c.field-meta.xml
<CustomField>
    <fullName>ActivityStatus__c</fullName>
    <description>Travel agency activity status</description>
    <required>true</required>
    <label>Activity Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Limited Access</fullName>
                <label>Limited</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TravelAgency__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Travel agency level</description>
    <required>true</required>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Level A</fullName>
                <default>true</default>
                <label>A</label>
            </value>
            <value>
                <fullName>Level B</fullName>
                <label>B</label>
            </value>
            <value>
                <fullName>Level C</fullName>
                <label>C</label>
            </value>
            <value>
                <fullName>Level D</fullName>
                <label>D</label>
            </value>
            <value>
                <fullName>Level E</fullName>
                <label>E</label>
            </value>
            <value>
                <fullName>Level F</fullName>
                <label>F</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/general-test/test-factory/classes/GENERAL_TestTravelAgencyFactory.cls
/********************************************************************
* This class is for generating test data for TravelAgency__C object
********************************************************************/

@isTest
public with sharing class GENERAL_TestTravelAgencyFactory {

    /**
     * This inner class is for changing the delault field values
     * Setter: withName, withLevel, withActivityStatus (return this)
     * Getter: get (return TravelAgency__c)
    **/
    public class Single {

        private TravelAgency__c travelAgency;

        public Single withName(String value) {
            try {
                this.travelAgency.Name = value;
            } catch (Exception ex) {
                System.debug('Incorrect Name value in method withName: ' + ex.getMessage());
            }
            return this;
        }

        public Single withLevel(String value) {
            try {
                this.travelAgency.Level__c = value;
            } catch (Exception ex) {
                System.debug('Incorrect Level__c value in method withLevel: ' + ex.getMessage());
            }
            return this;
        }

        public Single withActivityStatus(String value) {
            try {
                this.travelAgency.ActivityStatus__c = value;
            } catch (Exception ex) {
                System.debug('Incorrect ActivityStatus__c value in method withActivityStatus: ' + ex.getMessage());
            }
            return this;
        }

        public TravelAgency__c get() {
            insert this.travelAgency;
            return this.travelAgency;
        }
    }

    /**
     * This method creates only one TravelAgency__c instance
     * For futher use TravelAgency__c instance it is necessary to call get() method
     * (createSingle().get())
    **/
    public static Single createSingle() {
        Single single = new Single();
        single.travelAgency = GENERAL_TestTravelAgencyCreator.create(1)[0];
        return single;
    }

    /**
     * This method creates List<TravelAgency__c> by input number
    **/
    public static List<TravelAgency__c> createByNumber(Integer travelAgencyNumber) {
        List<TravelAgency__c> travelAgencies = GENERAL_TestTravelAgencyCreator.create(travelAgencyNumber);
        insert travelAgencies;
        return travelAgencies;
    }
}