force-app/main/default/objects/Tour__c/Tour__c.object-meta.xml
<CustomObject>
    <description>Tour information</description>
    <label>Tour</label>
    <nameField>
        <label>Tour Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TourSaleStatus__c/TourSaleStatus__c.object-meta.xml
<CustomObject>
    <description>Tour sale status</description>
    <label>Tour Sale Status</label>
    <nameField>
        <label>Name</label>
        <type>AutoNumber</type>
        <displayFormat>TSS-{000000}</displayFormat>
    </nameField>
    <pluralLabel>Tour Sale Status</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TourSaleStatus__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Price</description>
    <label>Price</label>
    <required>true</required>
    <type>Currency</type>
    <precision>18</precision>
    <scale>2</scale>
</CustomField>

force-app/main/default/objects/TourSaleStatus__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Sale status</description>
    <required>true</required>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Sale</fullName>
                <default>true</default>
                <label>On Sale</label>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TourSaleStatus__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <description>Total price of the tour with a discount</description>
    <label>Total Price</label>
    <type>Currency</type>
    <precision>18</precision>
    <scale>2</scale>
    <formula>ROUND(Price__c - Price__c * Discount__c, 2)</formula>
</CustomField>

force-app/main/default/objects/TourSaleStatus__c/fields/Tour__c.field-meta.xml
<CustomField>
    <fullName>Tour__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Sale status related to the tour</inlineHelpText>
    <label>Tour</label>
    <referenceTo>Tour__c</referenceTo>
    <relationshipName>TSS_Tour</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/aep/selector/classes/TourSaleStatusSelector.cls
/**********************************************************************************
* This class contains methods for generating query to the TourSaleStatus__c object
**********************************************************************************/

public with sharing class TourSaleStatusSelector extends GENERAL_SObjectSelector {

    public SObjectType getSObjectType() {
        return TourSaleStatus__c.SObjectType;
    }

    /**
     * Defaulf fields of TourSaleStatus__c object
    **/
    public List<SObjectField> getSObjectFieldList() {
        return new List<SObjectField> {
            TourSaleStatus__c.Id,
            TourSaleStatus__c.Price__c,
            TourSaleStatus__c.TotalPrice__c,
            TourSaleStatus__c.Status__c
        };
    }

    /**
     * selectByTourId method selects TourSaleStatus__c by its Tour Id
    **/
    public List<TourSaleStatus__c> selectByTourId(Id tourId) {
        return Database.query(
            newQueryFactory()
                .setCondition('Tour__c = :tourId')
                .ToSOQl()
            );
    }
}