force-app/main/default/objects/Tour__c/Tour__c.object-meta.xml
<CustomObject>
    <description>Tour information</description>
    <label>Tour</label>
    <nameField>
        <label>Tour Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tours</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Tour__c/fields/GuestsNumber__c.field-meta.xml
<CustomField>
    <fullName>GuestsNumber__c</fullName>
    <description>Number of guests</description>
    <label>Guests number</label>
    <required>true</required>
    <type>Number</type>
    <precision>18</precision>
    <scale>0</scale>
</CustomField>

force-app/aep/service/classes/TourService.cls
/*******************************************************************
* This class contains methods for working with the Tour__c object
*******************************************************************/

public with sharing class TourService {

    /**
     * This method called from TourTrigger wher guests count changed
    **/
    public void checkGuestsNumber(List<Tour__c> newRecordsList, Map<Id, Tour__c> oldRecordsMap) {
        try {
            for (Tour__c newTour : newRecordsList) {
                if (oldRecordsMap == null) continue;
                Tour__c oldTour = oldRecordsMap.get(newTour.Id);
                if (oldTour != null && oldTour.GuestsNumber__c != newTour.GuestsNumber__c) {
                    TourSaleStatusService.recalcTourPrice(newTour.Id, (Integer)oldTour.GuestsNumber__c, (Integer)oldTour.GuestsNumber__c);
                }
            }
        } catch (Exception ex) {
            System.debug(LoggingLevel.ERROR, ex.getMessage());
        }
    }
}